export const inputProps = [
  {
    id: "nome",
    name: "nome",
    label: "Nome",
    placeholder: "Nome do Projeto",
    type: "text",
  },
  {
    id: "pronac",
    name: "pronac",
    label: "PRONAC",
    placeholder: "PRONAC do Projeto",
    type: "number",
  },
  {
    id: "ano",
    name: "ano_projeto",
    label: "Ano",
    placeholder: "Ano do Projeto",
    type: "number",
  },
  {
    id: "segmento",
    name: "segmento",
    label: "Segmento",
    placeholder: "Segmento do Projeto",
    type: "text",
  },
  {
    id: "area",
    name: "area",
    label: "Área",
    placeholder: "Área do Projeto",
    type: "select",
    options: ['', 'Artes Cênicas', 'Artes Visuais', 'Audiovisual', 'Humanidades', 'Música', 'Patrimônio Cultural']
  },
  {
    id: "uf",
    name: "uf",
    label: "UF",
    placeholder: "UF do Projeto",
    type: "text",
  },
  {
    id: "municipio",
    name: "municipio",
    label: "Município",
    placeholder: "Município do Projeto",
    type: "text",
  },
  {
    id: "data_inicio",
    name: "data_inicio",
    label: "Início",
    placeholder: "Início do Projeto",
    type: "date",
  },
  {
    id: "data_termino",
    name: "data_termino",
    label: "Término",
    placeholder: "Término do Projeto",
    type: "date",
  },
  {
    id: "situacao",
    name: "situacao",
    label: "Situação",
    placeholder: "Situação do Projeto",
    type: "text",
  },
  {
    id: "mecanismo",
    name: "mecanismo",
    label: "Mecanismo",
    placeholder: "Mecanismo do Projeto",
    type: "text",
  },
  {
    id: "enquadramento",
    name: "enquadramento",
    label: "Enquadramento",
    placeholder: "Enquadramento do Projeto",
    type: "text",
  },
  {
    id: "valor_captado",
    name: "valor_captado",
    label: "Valor Captado",
    placeholder: "Valor Captado do Projeto",
    type: "number",
  },
  {
    id: "valor_aprovado",
    name: "valor_aprovado",
    label: "Valor Aprovado",
    placeholder: "Valor Aprovado do Projeto",
    type: "number",
  },
  {
    id: "acessibilidade",
    name: "acessibilidade",
    label: "Acessibilidade",
    type: "textarea",
  },
  {
    id: "objetivos",
    name: "objetivos",
    label: "Objetivos",
    placeholder: "Objetivos do Projeto",
    type: "text",
  },
  {
    id: "justificativa",
    name: "justificativa",
    label: "Justificativa",
    placeholder: "Justificativa do Projeto",
    type: "text",
  },
  {
    id: "etapa",
    name: "etapa",
    label: "Etapa",
    placeholder: "Etapa do Projeto",
    type: "text",
  },
  {
    id: "ficha_tecnica",
    name: "ficha_tecnica",
    label: "Ficha Técnica",
    type: "textarea",
  },
  {
    id: "impacto_ambiental",
    name: "impacto_ambiental",
    label: "Impacto Ambiental",
    placeholder: "Impacto Ambiental do Projeto",
    type: "text",
  },
  {
    id: "especificacao_tecnica",
    name: "especificacao_tecnica",
    label: "Especificação Técnica",
    placeholder: "Especificação Técnica do Projeto",
    type: "text",
  },
  {
    id: "providencia",
    name: "providencia",
    label: "Providência",
    placeholder: "Providência do Projeto",
    type: "text",
  },
  {
    id: "democratizacao",
    name: "democratizacao",
    label: "Democratização",
    placeholder: "Democratização do Projeto",
    type: "text",
  },
  {
    id: "sinopse",
    name: "sinopse",
    label: "Sinopse",
    type: "textarea",
  },
  {
    id: "resumo",
    name: "resumo",
    label: "Resumo",
    type: "textarea",
  },
  {
    id: "valor_projeto",
    name: "valor_projeto",
    label: "Valor Projeto",
    placeholder: "Valor do Projeto",
    type: "number",
  },
  {
    id: "outras_fontes",
    name: "outras_fontes",
    label: "Outras Fontes",
    placeholder: "Outras Fontes do Projeto",
    type: "text",
  },
  {
    id: "valor_proposta",
    name: "valor_proposta",
    label: "Valor Proposta",
    placeholder: "Valor Proposta do Projeto",
    type: "number",
  },
  {
    id: "valor_solicitado",
    name: "valor_solicitado",
    label: "Valor Solicitado",
    placeholder: "Valor Solicitado do Projeto",
    type: "number",
  },
  {
    id: "objetivo",
    name: "objetivo",
    label: "Objetivo",
    type: "textarea",
  },
  {
    id: "estrategia_execucao",
    name: "estrategia_execucao",
    label: "Estratégia de execução",
    placeholder: "Estratégia de execução do Projeto",
    type: "text",
  },
  {
    id: "link_incentivadores",
    name: "link_incentivadores",
    label: "Link incentivadores",
    placeholder: "Link de incentivadores do Projeto",
    type: "url",
  },
];
